version: '3.4'

services:
  play.catalog.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
    ports:
      - "5000"
      - "5001"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/httpcd \cds:ro