# docker run -d --rm --name mongo -p 27017:27017 --v mongodbdata://data/db mongo

version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mogo
    ports:
     - 27017:27017
    volumes:
     - mongodbdata:/data/db

  play.catalog.service:
    image: ${DOCKER_REGISTRY-}playcatalogservice
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  mongodbdata:
